# This is a basic workflow to help you get started with Actions

name: Deploy-Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'some variable'
        required: true
        # default: 'staging'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo ${{github.event.inputs.environment}}
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
